// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: httpheader.proto

package proto

import (
	"reflect"
	"sync"
	"unsafe"

	"google.golang.org/protobuf/reflect/protoreflect"
	"google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RequestHeader 请求头
type RequestHeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tenant        uint64                 `protobuf:"varint,1,opt,name=tenant,proto3" json:"tenant,omitempty"`                              // 租户id
	Version       uint32                 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`                            // 客户端版本
	RequestType   uint32                 `protobuf:"varint,3,opt,name=request_type,json=requestType,proto3" json:"request_type,omitempty"` // 请求类型 0-rpc 请求 1-http 请求 2-web 请求
	RequestId     uint64                 `protobuf:"varint,4,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`       // 请求唯一id
	TraceId       string                 `protobuf:"bytes,5,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`              // trace_id
	Timestamp     uint64                 `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                        // 请求时间戳（精确到毫秒）
	Timeout       uint32                 `protobuf:"varint,7,opt,name=timeout,proto3" json:"timeout,omitempty"`                            // 请求超时时间，单位ms
	Caller        string                 `protobuf:"bytes,8,opt,name=caller,proto3" json:"caller,omitempty"`                               // 主调服务的名称 tenant.app.server.service
	Callee        string                 `protobuf:"bytes,9,opt,name=callee,proto3" json:"callee,omitempty"`                               // 被调服务的路由名称 app.server.service/func
	Appid         uint64                 `protobuf:"varint,10,opt,name=appid,proto3" json:"appid,omitempty"`                               // appid
	Compress      uint32                 `protobuf:"varint,11,opt,name=compress,proto3" json:"compress,omitempty"`                         // 是否压缩 1-压缩；0-不压缩(默认)
	Ip            string                 `protobuf:"bytes,12,opt,name=ip,proto3" json:"ip,omitempty"`                                      // ip地址
	AuthRand      uint32                 `protobuf:"varint,13,opt,name=auth_rand,json=authRand,proto3" json:"auth_rand,omitempty"`         // 随机生成 0-99999999 的数字，相同 timestamp 不允许出现同样的 ip、auth_rand。为了避免碰撞，0-99999999，单机理论最大支持 1000 亿/秒的并发。
	Sign          string                 `protobuf:"bytes,14,opt,name=sign,proto3" json:"sign,omitempty"`                                  // sign 签名，为 md5(appid+secret+version+request_type+query_mode+request_id+trace_id+timestamp+timeout+caller+compress+auth_rand)
	Bak           string                 `protobuf:"bytes,15,opt,name=bak,proto3" json:"bak,omitempty"`                                    // 备用
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestHeader) Reset() {
	*x = RequestHeader{}
	mi := &file_httpheader_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestHeader) ProtoMessage() {}

func (x *RequestHeader) ProtoReflect() protoreflect.Message {
	mi := &file_httpheader_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestHeader.ProtoReflect.Descriptor instead.
func (*RequestHeader) Descriptor() ([]byte, []int) {
	return file_httpheader_proto_rawDescGZIP(), []int{0}
}

func (x *RequestHeader) GetTenant() uint64 {
	if x != nil {
		return x.Tenant
	}
	return 0
}

func (x *RequestHeader) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *RequestHeader) GetRequestType() uint32 {
	if x != nil {
		return x.RequestType
	}
	return 0
}

func (x *RequestHeader) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *RequestHeader) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *RequestHeader) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *RequestHeader) GetTimeout() uint32 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

func (x *RequestHeader) GetCaller() string {
	if x != nil {
		return x.Caller
	}
	return ""
}

func (x *RequestHeader) GetCallee() string {
	if x != nil {
		return x.Callee
	}
	return ""
}

func (x *RequestHeader) GetAppid() uint64 {
	if x != nil {
		return x.Appid
	}
	return 0
}

func (x *RequestHeader) GetCompress() uint32 {
	if x != nil {
		return x.Compress
	}
	return 0
}

func (x *RequestHeader) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *RequestHeader) GetAuthRand() uint32 {
	if x != nil {
		return x.AuthRand
	}
	return 0
}

func (x *RequestHeader) GetSign() string {
	if x != nil {
		return x.Sign
	}
	return ""
}

func (x *RequestHeader) GetBak() string {
	if x != nil {
		return x.Bak
	}
	return ""
}

// ResponseHeader 响应头
type ResponseHeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       uint32                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`                      // 客户端版本
	RequestId     uint64                 `protobuf:"varint,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"` // 请求唯一id
	Compress      uint32                 `protobuf:"varint,3,opt,name=compress,proto3" json:"compress,omitempty"`                    // 返回结果是否压缩 1-压缩；0-不压缩(默认)
	Err           *Error                 `protobuf:"bytes,4,opt,name=err,proto3" json:"err,omitempty"`                               // 返回错误
	IsNil         bool                   `protobuf:"varint,5,opt,name=is_nil,json=isNil,proto3" json:"is_nil,omitempty"`             // 返回是否为空
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseHeader) Reset() {
	*x = ResponseHeader{}
	mi := &file_httpheader_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseHeader) ProtoMessage() {}

func (x *ResponseHeader) ProtoReflect() protoreflect.Message {
	mi := &file_httpheader_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseHeader.ProtoReflect.Descriptor instead.
func (*ResponseHeader) Descriptor() ([]byte, []int) {
	return file_httpheader_proto_rawDescGZIP(), []int{1}
}

func (x *ResponseHeader) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ResponseHeader) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *ResponseHeader) GetCompress() uint32 {
	if x != nil {
		return x.Compress
	}
	return 0
}

func (x *ResponseHeader) GetErr() *Error {
	if x != nil {
		return x.Err
	}
	return nil
}

func (x *ResponseHeader) GetIsNil() bool {
	if x != nil {
		return x.IsNil
	}
	return false
}

type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          int32                  `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"` //错误类型
	Code          int32                  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"` //错误码
	Msg           string                 `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`    //错误信息
	Sql           string                 `protobuf:"bytes,4,opt,name=sql,proto3" json:"sql,omitempty"`    //查询语句
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_httpheader_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_httpheader_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_httpheader_proto_rawDescGZIP(), []int{2}
}

func (x *Error) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *Error) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Error) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *Error) GetSql() string {
	if x != nil {
		return x.Sql
	}
	return ""
}

var File_httpheader_proto protoreflect.FileDescriptor

const file_httpheader_proto_rawDesc = "" +
	"\n" +
	"\x10httpheader.proto\"\x8b\x03\n" +
	"\rRequestHeader\x12\x16\n" +
	"\x06tenant\x18\x01 \x01(\x04R\x06tenant\x12\x18\n" +
	"\aversion\x18\x02 \x01(\rR\aversion\x12!\n" +
	"\frequest_type\x18\x03 \x01(\rR\vrequestType\x12\x1d\n" +
	"\n" +
	"request_id\x18\x04 \x01(\x04R\trequestId\x12\x19\n" +
	"\btrace_id\x18\x05 \x01(\tR\atraceId\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x04R\ttimestamp\x12\x18\n" +
	"\atimeout\x18\a \x01(\rR\atimeout\x12\x16\n" +
	"\x06caller\x18\b \x01(\tR\x06caller\x12\x16\n" +
	"\x06callee\x18\t \x01(\tR\x06callee\x12\x14\n" +
	"\x05appid\x18\n" +
	" \x01(\x04R\x05appid\x12\x1a\n" +
	"\bcompress\x18\v \x01(\rR\bcompress\x12\x0e\n" +
	"\x02ip\x18\f \x01(\tR\x02ip\x12\x1b\n" +
	"\tauth_rand\x18\r \x01(\rR\bauthRand\x12\x12\n" +
	"\x04sign\x18\x0e \x01(\tR\x04sign\x12\x10\n" +
	"\x03bak\x18\x0f \x01(\tR\x03bak\"\x96\x01\n" +
	"\x0eResponseHeader\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\x04R\trequestId\x12\x1a\n" +
	"\bcompress\x18\x03 \x01(\rR\bcompress\x12\x18\n" +
	"\x03err\x18\x04 \x01(\v2\x06.ErrorR\x03err\x12\x15\n" +
	"\x06is_nil\x18\x05 \x01(\bR\x05isNil\"S\n" +
	"\x05Error\x12\x12\n" +
	"\x04type\x18\x01 \x01(\x05R\x04type\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x03 \x01(\tR\x03msg\x12\x10\n" +
	"\x03sql\x18\x04 \x01(\tR\x03sqlb\x06proto3"

var (
	file_httpheader_proto_rawDescOnce sync.Once
	file_httpheader_proto_rawDescData []byte
)

func file_httpheader_proto_rawDescGZIP() []byte {
	file_httpheader_proto_rawDescOnce.Do(func() {
		file_httpheader_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_httpheader_proto_rawDesc), len(file_httpheader_proto_rawDesc)))
	})
	return file_httpheader_proto_rawDescData
}

var file_httpheader_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_httpheader_proto_goTypes = []any{
	(*RequestHeader)(nil),  // 0: RequestHeader
	(*ResponseHeader)(nil), // 1: ResponseHeader
	(*Error)(nil),          // 2: Error
}
var file_httpheader_proto_depIdxs = []int32{
	2, // 0: ResponseHeader.err:type_name -> Error
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_httpheader_proto_init() }
func file_httpheader_proto_init() {
	if File_httpheader_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_httpheader_proto_rawDesc), len(file_httpheader_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_httpheader_proto_goTypes,
		DependencyIndexes: file_httpheader_proto_depIdxs,
		MessageInfos:      file_httpheader_proto_msgTypes,
	}.Build()
	File_httpheader_proto = out.File
	file_httpheader_proto_goTypes = nil
	file_httpheader_proto_depIdxs = nil
}
