// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: webheader.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// WebReqHeader WEB 请求头
type WebReqHeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`                               // 客户端版本
	RequestId     uint64                 `protobuf:"varint,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`         // 请求唯一id
	Timestamp     uint64                 `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                          // 请求时间戳（精确到毫秒）
	Ip            string                 `protobuf:"bytes,4,opt,name=ip,proto3" json:"ip,omitempty"`                                         // ip地址
	Tenant        uint64                 `protobuf:"varint,5,opt,name=tenant,proto3" json:"tenant,omitempty"`                                // 租户id
	UserIdentity  *UserIdentity          `protobuf:"bytes,6,opt,name=user_identity,json=userIdentity,proto3" json:"user_identity,omitempty"` // 用户身份
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebReqHeader) Reset() {
	*x = WebReqHeader{}
	mi := &file_webheader_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebReqHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebReqHeader) ProtoMessage() {}

func (x *WebReqHeader) ProtoReflect() protoreflect.Message {
	mi := &file_webheader_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebReqHeader.ProtoReflect.Descriptor instead.
func (*WebReqHeader) Descriptor() ([]byte, []int) {
	return file_webheader_proto_rawDescGZIP(), []int{0}
}

func (x *WebReqHeader) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *WebReqHeader) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *WebReqHeader) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *WebReqHeader) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *WebReqHeader) GetTenant() uint64 {
	if x != nil {
		return x.Tenant
	}
	return 0
}

func (x *WebReqHeader) GetUserIdentity() *UserIdentity {
	if x != nil {
		return x.UserIdentity
	}
	return nil
}

// WebRespHeader Web响应头
type WebRespHeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`                       // 客户端版本
	RequestId     uint64                 `protobuf:"varint,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"` // 请求唯一id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebRespHeader) Reset() {
	*x = WebRespHeader{}
	mi := &file_webheader_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebRespHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebRespHeader) ProtoMessage() {}

func (x *WebRespHeader) ProtoReflect() protoreflect.Message {
	mi := &file_webheader_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebRespHeader.ProtoReflect.Descriptor instead.
func (*WebRespHeader) Descriptor() ([]byte, []int) {
	return file_webheader_proto_rawDescGZIP(), []int{1}
}

func (x *WebRespHeader) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *WebRespHeader) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

type UserIdentity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Userid        uint64                 `protobuf:"varint,1,opt,name=userid,proto3" json:"userid,omitempty"`
	Account       string                 `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
	Nickname      string                 `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserIdentity) Reset() {
	*x = UserIdentity{}
	mi := &file_webheader_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserIdentity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserIdentity) ProtoMessage() {}

func (x *UserIdentity) ProtoReflect() protoreflect.Message {
	mi := &file_webheader_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserIdentity.ProtoReflect.Descriptor instead.
func (*UserIdentity) Descriptor() ([]byte, []int) {
	return file_webheader_proto_rawDescGZIP(), []int{2}
}

func (x *UserIdentity) GetUserid() uint64 {
	if x != nil {
		return x.Userid
	}
	return 0
}

func (x *UserIdentity) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *UserIdentity) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

var File_webheader_proto protoreflect.FileDescriptor

const file_webheader_proto_rawDesc = "" +
	"\n" +
	"\x0fwebheader.proto\"\xc1\x01\n" +
	"\fWebReqHeader\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\x04R\trequestId\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x04R\ttimestamp\x12\x0e\n" +
	"\x02ip\x18\x04 \x01(\tR\x02ip\x12\x16\n" +
	"\x06tenant\x18\x05 \x01(\x04R\x06tenant\x122\n" +
	"\ruser_identity\x18\x06 \x01(\v2\r.UserIdentityR\fuserIdentity\"H\n" +
	"\rWebRespHeader\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\x04R\trequestId\"\\\n" +
	"\fUserIdentity\x12\x16\n" +
	"\x06userid\x18\x01 \x01(\x04R\x06userid\x12\x18\n" +
	"\aaccount\x18\x02 \x01(\tR\aaccount\x12\x1a\n" +
	"\bnickname\x18\x03 \x01(\tR\bnicknameb\x06proto3"

var (
	file_webheader_proto_rawDescOnce sync.Once
	file_webheader_proto_rawDescData []byte
)

func file_webheader_proto_rawDescGZIP() []byte {
	file_webheader_proto_rawDescOnce.Do(func() {
		file_webheader_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_webheader_proto_rawDesc), len(file_webheader_proto_rawDesc)))
	})
	return file_webheader_proto_rawDescData
}

var file_webheader_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_webheader_proto_goTypes = []any{
	(*WebReqHeader)(nil),  // 0: WebReqHeader
	(*WebRespHeader)(nil), // 1: WebRespHeader
	(*UserIdentity)(nil),  // 2: UserIdentity
}
var file_webheader_proto_depIdxs = []int32{
	2, // 0: WebReqHeader.user_identity:type_name -> UserIdentity
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_webheader_proto_init() }
func file_webheader_proto_init() {
	if File_webheader_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_webheader_proto_rawDesc), len(file_webheader_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_webheader_proto_goTypes,
		DependencyIndexes: file_webheader_proto_depIdxs,
		MessageInfos:      file_webheader_proto_msgTypes,
	}.Build()
	File_webheader_proto = out.File
	file_webheader_proto_goTypes = nil
	file_webheader_proto_depIdxs = nil
}
