server:
  log_path: "/data/app/logs/super_server"
  log_level: 1  # ERROR=1, DEBUG=2, WARNING=3, NOTICE=4, INFO=5, ALL=6

zone:
  zone_info:
    - zone_id: 1
      zone_name: "世外桃园"
      hequ: 0
      hot: "爆满"
      status: 1
      socket: "s1"
      port: 9277
      time: "2020-03-28 10:00:00"
  source_zone:
    1: 0
  recommend_zone: [1]

wx_app:
  wxea88f4e276e7aa54:
    app_id: "wxea88f4e276e7aa54"
    secret: "961f7645de40fedeef1b39e05d09df17"
  wxd81f88e32bd18a45:
    app_id: "wxd81f88e32bd18a45"
    secret: "56cb2ea6dd85c0ce9f0b747b4b137ea8"
  wx06692a054e505147:
    app_id: "wx06692a054e505147"
    secret: "6f2d14cf1a5b3e8f4b471867c497f179"

constants:
  weixin_open_id_url: "https://api.weixin.qq.com/sns/jscode2session?"
  weixin_snsapi_user_info_url: "https://api.weixin.qq.com/sns/userinfo?"
  token_generate_key: "iLoveGaoquMeMeDa"
  rank_per_page: 10
